### ISSUE TITLE
Sequence Name

### ISSUE THREAD

**Issue by aassie** [igorrcosta/phylomito#1]
Hello,

Thank you for such a useful tool, this is exactly what I was poorly trying to set up on my own.

I have a question about the output format, in my case I end up with sequences where the name has been replaced by a number.  Is there any way to match these number back to the name of the original sequence ?

Thank you very much,

Adrien Assié

**Comment by igorrcosta** [comment]
Hi!

Phylomito will convert the numbers back to the species name in the *_final_tree.txt file. If you want to check the alignments, the file you are looking for is species_code.txt. It matches the number keys with the species.

Thanks for your feedback! I'm glad to hear it is useful for you :)

**Comment by aassie** [comment]
Thank you for replying to me, 
I will have a look on it as soon as possible !
